### ISSUE TITLE
Does not show help as entered `?`

### ISSUE THREAD

**Issue by maekawatoshiki** [p-e-w/savage#9] opened 2022-03-17 16:52 UTC
It doesn't show help even if I type `?`. Is it not implemented for now?

<img width="501" alt="" src="https://user-images.githubusercontent.com/9913176/158852428-058394f1-17bf-452a-bbb5-232501e39664.png">

**Comment by p-e-w** [comment] 2022-03-18 06:56
Duplicate of #5.

**Closed by p-e-w** 2022-03-18 06:56 UTC
